---
title: "lesson4_student"
output: html_document
---

```{r setup, include=FALSE}
install.packages('ggplot2')
library(ggplot2)

data("diamonds")
df <- diamonds
```
# 钻石

```{r}
?diamonds
summary(df)
dim(df)
```

# 价格直方图

```{r}
ggplot(aes(x = price), data = df) +
  geom_histogram(binwidth = 500,color = 'black', fill = '#099DD9')+
  scale_x_continuous(limits = c(0, 20000), breaks = seq(0, 20000, 2000)) 
```

# 价格直方图小结

```{r}
sum(df$price < 500)
sum(df$price < 200)
sum(df$price >= 15000)
```

# 钻石数量
```{r}
ggplot(aes(x = price), data = df) +
  geom_histogram(binwidth = 1 ,color = 'black', fill = '#099DD9')+
  scale_x_continuous(limits = c(580, 620), breaks = seq(580, 620, 5)) 
```

# 廉价钻石

```{r}
p1 <- ggplot(aes(x = price), data = df) +
  geom_histogram(binwidth = 500,color = 'black', fill = '#099DD9') +
  scale_x_continuous(limits = c(0, 20000), breaks = seq(0, 20000, 5000)) 
p1 + facet_wrap(~cut)
```
# 切工-价格直方图?
```{r}
p1 <- ggplot(aes(x = price), data = df) +
  geom_histogram(binwidth = 500,color = 'black', fill = '#099DD9') +
  scale_x_continuous(limits = c(0, 20000), breaks = seq(0, 20000, 10000)) 
p1 + facet_grid(. ~ cut)
```

# 切工-价格
```{r}
p1 <- ggplot(aes(x = price/carat), data = df) +
  geom_histogram(binwidth = 500,color = 'black', fill = '#099DD9') +
  scale_x_continuous(limits = c(0, 20000), breaks = seq(0, 20000, 2000)) + 
  facet_wrap(~cut) 
p1
```

# 价格箱线图
```{r}
install.packages('gridExtra')
library(gridExtra)
```

```{r}
p1 <- ggplot(aes(y = price ,x = cut ), data = df) +
  geom_boxplot(color = 'black', fill = '#099DD9') +
  coord_cartesian(ylim = c(0,7000))
p2 <- ggplot(aes(y = price ,x = clarity ), data = df) +
  geom_boxplot(color = 'black', fill = '#099DD9') +
  coord_cartesian(ylim = c(0,7000))
p3 <- ggplot(aes(y = price ,x = color ), data = df) +
  geom_boxplot(color = 'black', fill = '#099DD9') +
  coord_cartesian(ylim = c(0,10000))

grid.arrange(p1,p2,p3, ncol=1)
```

# 四分位数间距 — IQR
```{r}
color_d <- subset(df, color < 'E')
half_IQR <- IQR(color_d$price)/2
max(color_d$price) - (median(color_d$price) + half_IQR)
median(color_d$price) - half_IQR

color_j <- subset(df, color > 'I')
half_IQR = IQR(color_j$price)/2
median(color_j$price) + half_IQR
median(color_j$price) - half_IQR

IQR(color_j$price)
IQR(color_d$price)
```